name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          configuration-path: ".github/labels.yaml"
          sync-labels: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
